# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69fc496d1056564281e3e8cec69c4750a25159e384d3d993995e7fdb93d9fda78ab9fd782670891c5a4119c9773b8d0f77ea1ffd5c859a75fbc39c626f733f1d

test:
  secret_key_base: dc4afbd7c33fd03d69bbcdd9c840bbf924b51ec640014de5ab1488cebe3665ecf82e1cfd1448de89bfb969556759266bcefe44fe197e6d047405eb1905f8d4a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
